// <auto-generated />
namespace EduMax.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Course_PK_AutoIncrement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course_PK_AutoIncrement));
        
        string IMigrationMetadata.Id
        {
            get { return "202108271403182_Course_PK_AutoIncrement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
