// <auto-generated />
namespace EduMax.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Lecture_Assignment_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lecture_Assignment_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202108301305526_Lecture_Assignment_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
