// <auto-generated />
namespace EduMax.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentCourse_Updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentCourse_Updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202108241506529_StudentCourse_Updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
