// <auto-generated />
namespace EduMax.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user_Credential_Annotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_Credential_Annotation));
        
        string IMigrationMetadata.Id
        {
            get { return "202109061415549_user_Credential_Annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
