// <auto-generated />
namespace EduMax.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_relation_in_Teacher_5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_relation_in_Teacher_5));
        
        string IMigrationMetadata.Id
        {
            get { return "202107242006599_change_relation_in_Teacher_5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
